"""add stock_restored to orders

Revision ID: 164072dcc4bb
Revises: bb9664b1eb45
Create Date: 2026-01-30 22:13:03.244188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164072dcc4bb'
down_revision = 'bb9664b1eb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_restored', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('stock_restored')

    # ### end Alembic commands ###
